# Generated by Django 5.2.7 on 2025-10-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMenu', '0003_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('creator_username', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('chat_log', models.FileField(blank=True, null=True, upload_to='chat_logs/', verbose_name='Лог чата')),
            ],
            options={
                'verbose_name': 'Архивная комната',
                'verbose_name_plural': 'Архивные комнаты',
                'ordering': ['-archived_at'],
            },
        ),
    ]
